baseurl: '/template1/'
exclude: ['README.md']
permalink: pretty
title: 'Department Name'

collections:
  admissions:
    output: true
    permalink: /admissions/:path/
  faculty:
    output: true
    permalink: /faculty/:path/
  aboutus:
    output: true
    permalink: /aboutus/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-environment-variables
